name: test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "packages/**/src/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - uses: tj-actions/changed-files@v37
      - run: pnpm lint && pnpm build.qwik
        if: contains(${{ steps.changed-files.outputs.all_changed_files }}, 'packages/qwik')
